apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: airflow-dev
  chart:
    repository: https://airflow-helm.github.io/charts/
    name: airflow
    version: 8.0.0
  values:
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    config:
      # AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "False"
      AIRFLOW__KUBERNETES__NAMESPACE: "dev"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "2.0.2-python3.7"
      # AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__BASE_URL: "https://localhost:8080/airflow-dev"
      # AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflow-dev-logs"
    executor: "KubernetesExecutor"
    dags:
      persistence:
        enabled: true
        size: 512Mi
        storageClass: aws-efs
        existingClaim: efs-storage-claim
        subPath: ""
      gitSync:
        enabled: true
        repo: "git@github.com:enniomorricone123/airflow-dags.git"
        branch: master
        repoSubPath: ""
        syncWait: 60
        sshSecret: "airflow-git-private-dags"
    ingress:
      enabled: true
      web:
        path: "airflow-dev"
    # web:
    #   extraVolumes:
    #     - name: "logs"
    #       persistentVolumeClaim:
    #         claimName: "efs-storage-claim"
      # extraVolumeMounts:
      #   - name: "logs"
      #     mountPath: "/opt/airflow/logs"
    logs:
      path: "/opt/airflow/logs"
      persistence: 
        enabled: true
        existingClaim: "efs-storage-claim"
        storageClass: aws-efs
        size: 512Mi
      
      